# Generated by Django 3.0.4 on 2020-03-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0004_auto_20200331_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
    ]
