# Generated by Django 3.0.4 on 2020-03-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0005_remove_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Texno', max_length=255, verbose_name='Имя'),
        ),
    ]
