# Generated by Django 3.0.4 on 2020-03-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0006_userprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='NickName', max_length=255, verbose_name='Имя'),
        ),
    ]
