# Generated by Django 3.0.4 on 2020-03-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0007_auto_20200331_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='Число дизлайков'),
        ),
        migrations.AddField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Число лайков'),
        ),
    ]
