# Generated by Django 3.0.4 on 2020-04-01 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0010_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 8, 9, 42, 931060, tzinfo=utc), verbose_name='Дата ответа'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(default='Texno', max_length=120, verbose_name='Заголовок ярлыка'),
        ),
    ]
