# Generated by Django 3.0.4 on 2020-04-01 09:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0014_auto_20200401_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='date_published',
        ),
        migrations.AddField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 9, 10, 25, 946333, tzinfo=utc), verbose_name='Дата ответа'),
        ),
    ]
