# Generated by Django 3.0.4 on 2020-04-01 09:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WEB', '0018_auto_20200401_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 9, 15, 28, 337307, tzinfo=utc), verbose_name='Дата ответа'),
        ),
    ]
